"""Emit the MS01 demo image as C arrays (ROM window + initialised RAM)."""

import sys

sys.path.insert(0, "work")
from ms01_run import load_s37, S37  # noqa: E402

OUT = "outputs/emulator/ms01_image.c"


def main() -> None:
    rom = load_s37(S37)
    ram = [rom.get(a, 0) for a in range(0x800)]              # 0x0000-0x07FF
    code = [rom.get(a, 0) for a in range(0x0800, 0x10000)]   # 0x0800-0xFFFF
    with open(OUT, "w") as f:
        f.write("/* generated by work/mk_ms01_image.py from MS01.S37 */\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const uint32_t ms01_rom_base = 0x0800;\n")
        f.write(f"const uint32_t ms01_rom_count = {len(code)};\n")
        f.write(f"uint16_t ms01_rom[{len(code)}] = {{\n")
        for i in range(0, len(code), 12):
            f.write("    " + " ".join(f"0x{v:04X}," for v in code[i:i + 12]) + "\n")
        f.write("};\n\n")
        f.write(f"uint16_t ms01_ram_init[{len(ram)}] = {{\n")
        for i in range(0, len(ram), 12):
            f.write("    " + " ".join(f"0x{v:04X}," for v in ram[i:i + 12]) + "\n")
        f.write("};\n")
    print(f"{OUT}: rom={len(code)} words, ram_init={len(ram)} words")


if __name__ == "__main__":
    main()
