// Turn a 64 KB SPCE061A image dump into the C array the emulator expects
// (base word address 0x8200, 32256 words = the image's first 0xFC00 bytes).
// usage: node tools/mk_fw_c.js <image.bin> <out.c> [symbol]
const fs = require('fs');
const img = fs.readFileSync(process.argv[2]);
const out = process.argv[3];
const sym = process.argv[4] || 'firmware_061';
const base = 0x8200;
const count = 32256;
if (img.length < count * 2) throw new Error('image too small');

const lines = [];
lines.push('/* generated by tools/mk_fw_c.js from ' + process.argv[2] + ' */');
lines.push('#include <stdint.h>');
lines.push('');
lines.push(`const uint16_t ${sym}_first = 0x${base.toString(16)};`);
lines.push(`const uint32_t ${sym}_count = ${count};`);
lines.push('');
lines.push(`const uint16_t ${sym}[${count}] = {`);
for (let i = 0; i < count; i += 12) {
  const row = [];
  for (let k = 0; k < 12 && i + k < count; k++) {
    row.push('0x' + img.readUInt16LE((i + k) * 2).toString(16).toUpperCase().padStart(4, '0'));
  }
  lines.push('    ' + row.join(', ') + (i + 12 < count ? ',' : ''));
}
lines.push('};');
fs.writeFileSync(out, lines.join('\n') + '\n');
console.log(`wrote ${out}: ${count} words from ${process.argv[2]} (symbol ${sym})`);
